apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: status-page-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: status-page-web
  template:
    metadata:
      labels:
        app: status-page-web
    spec:
      containers:
        - name: status-page-web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          env:
            DATABASE_NAME: statuspage
            DATABASE_USER: statuspage
            DATABASE_PASSWORD: "abcdefgh123456"
            DATABASE_HOST: postgres
            DATABASE_PORT: "5432"
            REDIS_HOST: redis
            REDIS_PORT: "6379"
            REDIS_TASKS_DB: "0"
            REDIS_CACHING_DB: "1"
            ALLOWED_HOSTS: "*"
            SECRET_KEY: "8cs)mx_OtgGHaZSKsV4Aw%Rahpe@22Ukj9S=UcJ1c$!@7Gwq%c"
          volumeMounts:
            - name: static-files
              mountPath: /opt/status-page/statuspage/static/
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3

imagePullSecrets:
  - name: regcred

volumes:
  - name: static-files
    hostPath:
      path: /home/user/finalProject/status-page/statuspage/static

