apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-files-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.static_files.size | default "5Gi" }}
  {{- if .Values.volumes.static_files.storageClassName }}
  storageClassName: {{ .Values.volumes.static_files.storageClassName }}
  {{- else }}
  storageClassName: "standard"  # Default to "standard" if storageClassName is not provided
  {{- end }}

