apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-at
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ .Values.fileSystemId }}
  directoryPerms: "700"
reclaimPolicy: Retain
volumeBindingMode: Immediate