postgres:
  image:
    repository: postgres
    tag: latest
  port: 5432
  hostname: db
  environment:
    POSTGRES_DB: "status-page"
    POSTGRES_USER: "status-page"
    POSTGRES_PASSWORD: "abcdefgh123456"
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U status-page -d status-page"]
    interval: 10s
    retries: 5
    timeout: 5s

redis:
  image:
    repository: redis
    tag: latest
  port: 6379
  replicas: 2
  healthcheck:
    test: ["CMD", "redis-cli", "ping"]
    interval: "10s"
    timeout: "3s"
    retries: 5

