redis:
  image: redis
  tag: latest  # Ensure the tag is specified here

postgres:
  image:
    repository: postgres
    tag: latest  # Ensure the tag is specified here
  environment:
    POSTGRES_DB: "status-page"  # Replace with the actual DB name
    POSTGRES_USER: "status-page"  # Replace with the actual Postgres user
    POSTGRES_PASSWORD: "abcdefgh123456"  # Replace with the actual password

