apiVersion: v1
kind: Service
metadata:
  name: status-page-django
  labels:
    app: django
spec:
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    app: django

