apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.nginx.ports.http }}
    targetPort: {{ .Values.nginx.ports.http }}
    protocol: TCP
    name: http
  - name: https  # Adding a name for the HTTPS port
    port: {{ .Values.nginx.ports.https }}  # The external port
    targetPort: 443
  selector:
    app: nginx


