apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  DATABASE_PASSWORD: YWJjZGVmZ2gxMjM0NTY=------------------
  DJANGO_SUPERUSER_PASSWORD: YWRtaW4xMjM=-------------------
