apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: {{ .Values.namespace }}
data:
  DATABASE_NAME: "{{ .Values.django.env.DATABASE_NAME }}"
  DATABASE_USER: "{{ .Values.django.env.DATABASE_USER }}"
  DATABASE_HOST: "{{ .Values.django.env.DATABASE_HOST }}"
  DATABASE_PORT: "{{ .Values.django.env.DATABASE_PORT }}"
  REDIS_HOST: "{{ .Values.django.env.REDIS_HOST }}"
  REDIS_PORT: "{{ .Values.django.env.REDIS_PORT }}"
  REDIS_TASKS_DB: "{{ .Values.django.env.REDIS_TASKS_DB }}"
  REDIS_CACHING_DB: "{{ .Values.django.env.REDIS_CACHING_DB }}"
  DJANGO_SUPERUSER_USERNAME: "{{ .Values.django.env.DJANGO_SUPERUSER_USERNAME }}"
  DJANGO_SUPERUSER_EMAIL: "{{ .Values.django.env.DJANGO_SUPERUSER_EMAIL }}"