apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{ .Values.namespace }}
  labels:
    app: nginx
spec:
  ports:
  - port: {{ .Values.nginx.ports.http }}
    targetPort: {{ .Values.nginx.ports.http }}
    protocol: TCP
    name: http
  selector:
    app: nginx

  
