apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.environment.POSTGRES_DB }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.environment.POSTGRES_USER }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.environment.POSTGRES_PASSWORD }}"
          livenessProbe:
            httpGet:
              path: /health
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
