---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-files-pvc
spec:
#  storageClassName: efs-at
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumes.static_files.size }}
