apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-redis-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Match this with the capacity of your PV
  storageClassName: manual  # Ensure this matches your PV's storage class
