name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3. Log in to Amazon ECR
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: ${{ secrets.AWS_REGION }}  # הוספתי את ה-region פה כדי שה-login יתבצע כראוי

    # 4. Build Docker image for the app
    - name: Build Docker image for the app
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME }}
        APP_IMAGE_TAG: 'app'
      run: |
        DOCKER_APP_IMAGE="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:${{ secrets.APP_IMAGE_TAG }}"
        docker build -t $DOCKER_APP_IMAGE -f docker/statuspage/Dockerfile .
        docker tag $DOCKER_APP_IMAGE $DOCKER_APP_IMAGE

    # 5. Build Docker image for nginx
    - name: Build Docker image for nginx
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME }}
        NGINX_IMAGE_TAG: 'nginx-app'
      run: |
        DOCKER_NGINX_IMAGE="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:${{ secrets.NGINX_IMAGE_TAG }}"
        docker build -t $DOCKER_NGINX_IMAGE -f docker/Dockerfile .
        docker tag $DOCKER_NGINX_IMAGE $DOCKER_NGINX_IMAGE

    # 6. Push Docker image for the app to Amazon ECR
    - name: Push Docker image for the app to Amazon ECR
      run: |
        docker push $DOCKER_APP_IMAGE

    # 7. Push Docker image for nginx to Amazon ECR
    - name: Push Docker image for nginx to Amazon ECR
      run: |
        docker push $DOCKER_NGINX_IMAGE
